export const iconMap = {
    transfer: 'arrow.uturn.right',
    recurringCalendar: 'arrow.trianglehead.2.clockwise.rotate.90',
    folder: 'folder.fill',
    folderThin: 'folder',
    openFolder: 'folder.fill',
    list: 'list.bullet',
    calendar: 'calendar',
    plannerStack: 'square.stack',
    lists: 'list.bullet.clipboard',
    coffee: 'cup.and.saucer.fill',
    add: 'plus',
    edit: 'pencil',
    note: 'note',
    chevronLeft: 'chevron.left',
    chevronDown: 'chevron.down',
    chevronUp: 'chevron.up',
    chevronRight: 'chevron.right',
    circleFilled: 'inset.filled.circle',
    circle: 'circle',
    trash: 'trash',
    more: 'ellipsis.circle',
    megaphone: 'megaphone',
    globe: 'globe.americas.fill',
    birthday: 'gift',
    clock: 'clock',
    message: 'message',
    messageFilled: 'checkmark.message',
    alert: 'exclamationmark.triangle',
    refresh: 'arrow.trianglehead.counterclockwise',
    refreshComplete: 'checkmark.arrow.trianglehead.counterclockwise',
    turnDown: 'arrow.turn.right.down',
    turnUp: 'arrow.turn.left.up',
};

export type TIconType = keyof typeof iconMap;

export const sizeMap = {
    xs: 10,
    ms: 12,
    s: 14,
    m: 16,
    l: 18,
    xl: 32
};