export const PLANNER_STORAGE_ID = 'PLANNER_STORAGE';

export const PLANNER_SETS_STORAGE_ID = 'PLANNER_SETS_STORAGE';

export const BIRTHDAY_STORAGE_ID = 'BIRTHDAY_STORAGE';

export const CHECKLISTS_STORAGE_ID = 'CHECKLISTS_STORAGE';

export const ROOT_CHECKLIST_FOLDER_KEY = 'ROOT_FOLDER_ID';

export const DEADLINE_LIST_KEY = 'DEADLINE_LIST_KEY';