import { SMALL_MARGIN } from "../../constants/layout";

const CALENDAR_ICON_SIZE_CONST = 22;
const DATESTAMP_ICON_SIZE_CONST = 42;

export enum EPlannerCarouselLayout {
    CALENDAR_ICON_SIZE = CALENDAR_ICON_SIZE_CONST,
    DATESTAMP_ICON_SIZE = DATESTAMP_ICON_SIZE_CONST,
    CAROUSEL_HEIGHT = CALENDAR_ICON_SIZE_CONST + DATESTAMP_ICON_SIZE_CONST + SMALL_MARGIN * 2

}