export enum EDeleteFunctionKey {
    FOLDER = 'FOLDER',
    CHECKLIST = 'CHECKLIST',
    RECURRING = 'RECURRING',
    PLANNER_EVENT = 'PLANNER_EVENT',
    PLANNER_SET = 'PLANNER_SET',
    COUNTDOWN = 'COUNTDOWN',
    RECURRING_WEEKDAY = 'RECURRING_WEEKDAY'
};