const CONTENT_HEIGHT_CONST = 20;
const NEW_ITEM_TRIGGER_HEIGHT_CONST = 16;

export enum EListLayout {
    CONTENT_HEIGHT = CONTENT_HEIGHT_CONST,
    NEW_ITEM_TRIGGER_HEIGHT = NEW_ITEM_TRIGGER_HEIGHT_CONST,
    ITEM_HEIGHT = CONTENT_HEIGHT_CONST + NEW_ITEM_TRIGGER_HEIGHT_CONST * 2
}