// ✅ 

export enum EListItemType {
    CHECKLIST = 'CHECKLIST', // TODO: remove

    RECURRING = 'RECURRING',
    RECURRING_WEEKDAY = 'RECURRING_WEEKDAY',
    COUNTDOWN = 'COUNTDOWN',
    PLANNER_SET = 'PLANNER_SET',
    FOLDER_ITEM = 'FOLDER_ITEM',
    BIRTHDAY = 'BIRTHDAY',
    EVENT = 'EVENT',
    CHECKLIST_ITEM = 'CHECKLIST_ITEM'
}