export enum EListType {
    CHECKLIST = 'CHECKLIST',
    RECURRING = 'RECURRING',
    PLANNER = 'PLANNER',
    RECURRING_WEEKDAY = 'RECURRING_WEEKDAY',
    COUNTDOWN = 'COUNTDOWN',
    PLANNER_SET = 'PLANNER_SET',
    FOLDER = 'FOLDER',
    BIRTHDAY = 'BIRTHDAY'
};