// ✅ 

export enum EStorageId {
  RECURRING_EVENT = 'RECURRING_EVENT_STORAGE',
  PLANNER_SETS = 'PLANNER_SETS_STORAGE',
  BIRTHDAY = 'BIRTHDAY_STORAGE',

  // LISTS
  PLANNER = 'PLANNER_STORAGE',
  FOLDER = 'FOLDER_STORAGE',

  // ITEMS
  EVENT = 'EVENT_STORAGE',
  ITEM = 'ITEM_STORAGE',
}
