export enum EStorageId {
  // LISTS
  RECURRING_PLANNER = 'RECURRING_PLANNER',
  PLANNER = 'PLANNER',
  UPCOMING_DATE_PLANNER = 'UPCOMING_DATE_PLANNER',
  FOLDER_ITEM = 'FOLDER_ITEM', // Special Case: Folder items are both lists and items

  // ITEMS
  PLANNER_EVENT = 'PLANNER_EVENT',
  CHECKLIST_ITEM = 'CHECKLIST_ITEM',
  RECURRING_PLANNER_EVENT = 'RECURRING_PLANNER_EVENT',
  UPCOMING_DATE_EVENT = 'UPCOMING_DATE_EVENT'
}
