// ✅ 

export enum EStorageId {
  PLANNER_SETS = 'PLANNER_SETS_STORAGE',
  BIRTHDAY = 'BIRTHDAY_STORAGE',

  // LISTS
  RECURRING_PLANNER = 'RECURRING_PLANNER',
  PLANNER = 'PLANNER',
  FOLDER_ITEM = 'FOLDER_ITEM', // Special Case: Folder items store lists of folder items.

  // ITEMS
  PLANNER_EVENT = 'EVENT',
  CHECKLIST_ITEM = 'ITEM_STORAGE',
  RECURRING_PLANNER_EVENT = 'RECURRING_EVENT_STORAGE',
}
