export enum EEventType {
  NON_CALENDAR = 'NON_CALENDAR_EVENT',
  CALENDAR_SINGLE_DAY = 'CALENDAR_SINGLE_DAY',
  CALENDAR_MULTI_DAY = 'CALENDAR_MULTI_DAY',
  CALENDAR_ALL_DAY = 'CALENDAR_ALL_DAY'
}

export enum ECarryoverEventType {
  START_EVENT = 'START_EVENT',
  END_EVENT = 'END_EVENT'
}
